build:
  image: bjodah/bjodahimg:latest
  environment:
    - PYNLEQ2_NLEQ2_ROOT_URL=$$PYNLEQ2_NLEQ2_ROOT_URL
  commands:
    - ./scripts/ci.sh pynleq2
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: pynleq2
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
